title: Noura Itani
logo: "/profile_picture.jpeg?raw=true" 
description: > 
  Data & Product at noon.com
  <br><br>
  Redefining the selling and buying experience with data-driven digital solutions
  <br><br>
  <a href="https://www.linkedin.com/in/noura-itani/">View My LinkedIn Profile</a>   
theme: jekyll-theme-minimal
